<script setup lang="ts">
definePageMeta({ layout: 'marketing' })
useSeoMeta({ title: 'Privacy notice', description: 'How Denalify handles personal data on its website and in the app.' })
defineOgImage('Denalify', { title: 'Privacy notice', description: 'How Denalify handles personal data on its website and in the app.', label: 'LEGAL' })
</script>

<template>
  <LegalArticle eyebrow="LEGAL / 01" title="Privacy notice" introduction="A clear account of the personal data involved when you visit Denalify, join the early-access list or use the app.">
    <div class="legal-notice"><p><strong>Publication detail to complete.</strong> The operator’s registered legal name, postal address and registration number must be inserted here before this notice is used as a final public legal document. Until then, contact <a href="mailto:contact@denalify.com">contact@denalify.com</a> with privacy questions.</p></div>
    <h2>1. Who is responsible</h2><p>The operator of Denalify is responsible for processing personal data collected through this website and, where it determines the purposes and means, through the Denalify application. For content that a customer uploads to a workspace on behalf of other people, the customer may be the controller and Denalify may act as a processor. A separate data processing agreement may be required for business customers.</p>
    <h2>2. What we process and why</h2><ul><li><strong>Early-access list:</strong> email address and time of signup, so we can respond to your request for access and send relevant launch updates. A voluntary referral source may also exist in older records. The legal basis for these emails is your consent (GDPR Article 6(1)(a)); you may withdraw it at any time.</li><li><strong>Account and workspace:</strong> account identifiers, email, profile details, organization membership, projects, tasks, comments, documents, files and other information you choose to add. We process these to provide the service and perform our contract (Article 6(1)(b)).</li><li><strong>Billing:</strong> plan, subscription and invoice information needed to provide paid services and meet accounting obligations (Articles 6(1)(b) and (c)). Payment card details are handled by the payment provider, not by this landing page.</li><li><strong>Security and support:</strong> login events, service logs, support messages and necessary technical information to protect accounts, investigate abuse and answer requests (Articles 6(1)(b) and (f)).</li></ul><p>We do not use the early-access form for unrelated marketing. New early-access signups do not require an IP address or geolocation lookup; older records may contain an IP address and country until they are reviewed and removed.</p>
    <h2>3. Who receives data</h2><p>Authorized team members and service providers may access only the information needed for hosting, email delivery, file storage, billing and support. Features you choose to connect can exchange relevant data with providers such as Google, GitHub, Discord, Slack and Stripe. Those providers may act under their own notices. We do not sell personal data.</p>
    <h2>4. International transfers</h2><p>Some providers may process information outside the European Economic Area. Where required, transfers must rely on an applicable adequacy decision or appropriate safeguards, such as standard contractual clauses. The actual provider list and transfer arrangements must be confirmed by the operator before publication.</p>
    <h2>5. How long data is kept</h2><p>We keep account and workspace data while the account or customer agreement is active, then for a limited period needed for recovery, disputes and legal duties. Billing records may be retained for legally required periods. Security logs are kept only as needed for security. Early-access addresses remain while the list is in use; you can request removal at any time. Specific production retention periods must be confirmed before publication.</p>
    <h2>6. Your choices and rights</h2><p>Subject to applicable law, you can request access, correction, deletion, restriction, portability or objection; you can withdraw consent without affecting earlier lawful processing. The app provides account export and deletion controls. Contact <a href="mailto:contact@denalify.com">contact@denalify.com</a> for other requests or to leave the early-access list. You can also complain to your data protection authority, including Poland’s <a href="https://uodo.gov.pl/">UODO</a> if it is your competent authority.</p>
    <h2>7. Cookies and changes</h2><p>Read the <NuxtLink to="/cookies">cookie notice</NuxtLink> for information about necessary storage. We will update this notice when practices change and display the new date above. Material changes should be communicated to affected users where required.</p>
  </LegalArticle>
</template>
