<script setup lang="ts">
definePageMeta({ layout: 'marketing' })
useSeoMeta({ title: 'Terms of service', description: 'Terms for using the Denalify application and website.' })
defineOgImage('Denalify', { title: 'Terms of service', description: 'Terms for using the Denalify application and website.', label: 'LEGAL' })
</script>

<template>
  <LegalArticle eyebrow="LEGAL / 03" title="Terms of service" introduction="The basic terms for creating a Denalify workspace and using the service.">
    <div class="legal-notice"><p><strong>Before public release:</strong> identify the legal service provider with registered name, address and registration details, and obtain legal review of these terms and the checkout flow. These terms are a working draft, not a substitute for those facts.</p></div>
    <h2>1. The service</h2><p>Denalify is an online workspace for organizing projects, tasks and related collaboration. Features, limits and availability can differ by plan. Current plan details are shown in the application before purchase. The public website describes the product but does not itself complete a paid subscription.</p>
    <h2>2. Accounts and workspaces</h2><p>Provide accurate information, keep your credentials secure and ensure that people you invite are permitted to access your workspace. Workspace administrators manage membership and permissions. You are responsible for activity under your account except where the law or our own failure provides otherwise. Tell us promptly about unauthorized access.</p>
    <h2>3. Your content</h2><p>You retain ownership of content you upload or create. You grant the operator the limited rights needed to store, process, display, back up and transmit that content to provide the service and integrations you enable. You must have the rights and lawful basis needed to submit the content. Do not submit prohibited material described in the <NuxtLink to="/acceptable-use">acceptable-use policy</NuxtLink>.</p>
    <h2>4. Plans and payments</h2><p>A free plan is available subject to published limits. Paid plans, taxes, currency, billing interval and any trial terms should be displayed at checkout before you commit. Subscription management and cancellation are available in the organization billing area. A cancellation normally stops renewal at the end of the current paid period; statutory refund and withdrawal rights remain unaffected. Contact <a href="mailto:contact@denalify.com">contact@denalify.com</a> about a billing dispute.</p>
    <h2>5. Availability and changes</h2><p>We work to keep the service available and secure, but we do not promise uninterrupted access or a specific uptime level unless a separate agreement says so. We may update features to improve the service or meet security and legal requirements. For material adverse changes, users should receive appropriate notice and any rights required by law.</p>
    <h2>6. Suspension and termination</h2><p>We may restrict access where reasonably necessary to address abuse, a security incident or a legal obligation, taking proportionate steps and providing notice when appropriate. You can stop using the service and request account deletion. Before leaving, use the available export controls to retrieve your data. Retention and deletion are described in the <NuxtLink to="/privacy">privacy notice</NuxtLink>.</p>
    <h2>7. Consumer rights and liability</h2><p>Nothing in these terms limits rights that cannot lawfully be excluded, including applicable consumer rights for digital services. Consumers buying at a distance may have a statutory withdrawal right, subject to legal conditions and exceptions; the checkout flow must supply the required information. Liability is governed by applicable law. These terms do not impose a blanket exclusion for our own misconduct.</p>
    <h2>8. Contact and disputes</h2><p>Send questions, complaints or withdrawal requests to <a href="mailto:contact@denalify.com">contact@denalify.com</a>. We will review them and respond as appropriate. Mandatory law and courts available to consumers continue to apply; a final governing-law clause requires the operator’s verified location.</p>
  </LegalArticle>
</template>
